### ISSUE TITLE
it dun wurk

### ISSUE THREAD

**Issue by Claycorp** [DoubleDoorDevelopment/JsonLootBags#1]
http://pastebin.com/YGfcQUZf

**Comment by Claycorp** [comment]
LOL i just looked at this to see if it was fixed yet and then bam a minute later ding.

**Comment by dries007** [comment]
Lol, i'll be writing docs after dentist
Op 3-aug.-2015 17:53 schreef "Claycorp" notifications@github.com:

**Comment by Claycorp** [comment]
alright.
