### ISSUE TITLE
Exception in server tick loop: CacheLoader returned null

### ISSUE THREAD

**Issue by Goldenlion5648** [DoubleDoorDevelopment/JsonLootBags#10]
CacheLoader returned null for key jsonlootbags:lootbotanialens.

https://hastebin.com/agowirewob.rb

**Comment by dries007** [comment]
Is it possible the loot table mentioned does not exist?

**Comment by Goldenlion5648** [comment]
The crash only occurred when the pack was put onto a server, the pack loading for the client was fine

**Comment by dries007** [comment]
Can you post your config please?

**Comment by Goldenlion5648** [comment]
I was able to figure it out. The loot table listed technically did not exist because the capitalization was different. My loot table used some upper cases. This worked fine when the game was being loaded for the client and logging into single player, but when put onto the server, the server would crash when some of the loot tables were capitalized. The strange part is that I only changed the capitalization of the file names, but I kept the capitalized letters in the loot table names when referencing them in the files for the bag files. Thanks for your help!

**Comment by dries007** [comment]
I'm surprised the games lets you start with non-lowercase letters in anything anymore. It's been discouraged in 1.11 and is no longer valid in 1.12. I recommend you make everything (that touches a registry, such as loot tables) lowercase.

No problem, enjoy the mod.
