### ISSUE TITLE
Request: Ability to spawn loot bag with player upon new world/server join

### ISSUE THREAD

**Issue by BBoldt** [DoubleDoorDevelopment/JsonLootBags#3]
Would be nice not to have to rely on a third party mod for this.

**Comment by dries007** [comment]
I'll look into it. Should't be too hard, but it won't be a priority.

**Comment by Claycorp** [comment]
Just in case that this never gets done or you need something ASAP....
I personally use Starting Inventory for inventory related stuff and Minetweaker for Loot related. I have not got into mob drops yet personally but have been told that mob properties is good.

http://minecraft.curseforge.com/projects/startinginventory
http://minetweaker3.powerofbytes.com/wiki/Tutorial:Loot
http://minecraft.curseforge.com/projects/mob-properties?gameCategorySlug=mc-mods&projectID=224298
