### ISSUE TITLE
Drops almost always the same

### ISSUE THREAD

**Issue by JasonMcRay** [DoubleDoorDevelopment/JsonLootBags#5]
I am using LootBags as a reward system for quests in my modpack. However I have noticed that in some cases for some players (from the looks of it, it is happening on servers only) the drops from the bags are always the same per type of bag. Not only in item given, but also in quantity.

https://github.com/JasonMcRay/InfiTech-1.7/tree/master/config/JsonLootBags - here are all my lootbags config files.

JsonLootBags: 0.0.0.7
Modpack: InfiTech 2

**Comment by dries007** [comment]
We internally use the Minecraft loot table system, so this _should_ be
impossible, but I'll have a look.

Op 16 aug. 2016 1:40 p.m. schreef "Jason McRay" notifications@github.com:

**Comment by Claycorp** [comment]
I'm having no issues on a test server I just tossed up. All the bags seem to cycle fine.

**Comment by JasonMcRay** [comment]
I am personally also not having the issue. It has been reported to me by one player. And I saw it happen on stream to one of the players as well... They got exactly the same stuff in same amount. Maybe its timed thing... Maybe the "loot-table" gets reset after certain time?

Also the player I got report from says, that he did not saw it happen from the beginning. He said that first few times it gave him different stuff.

**Comment by Claycorp** [comment]
Do you have a highlight/past broadcast/video of this happening you can link me to? I highly doubt it's an issue affecting one person specific person, as Dries said it uses vanilla systems. None of it should rely on anything about the player. I feel like they are just unlucky or the weights on the items are far off thus making something really common/super rare.

**Comment by JasonMcRay** [comment]
In my limited time I have found this:
https://www.youtube.com/watch?v=G4Zbz8VoVNA

Timestamps:
27:00 - Opens a Component Bag, gets 13 Electric Pistons
36:40 - Opens same bag, gets again exactly 13 Pistons.

The config file making this bag to work: (32640 is pistons)
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/JsonLootBags/componentBag.json

As you can see all the weights are same.
Also the min and max amounts are 3 - 8, he gets 13. I guess this is because he can get 1 or 2 item piles, so he probably got 2 item piles of the same item, twice in a row.

I think I will be able to dig up more, but its bit time consuming to find the parts. But from what I remember he got these pistons in same amount couple of times in future episodes.

**Comment by JasonMcRay** [comment]
Another one. Again exactly 13 Pistons: https://www.youtube.com/watch?v=M5L-9SKsqeI - 24:10
https://www.youtube.com/watch?v=tjMj6dBVBb0 - 5:40 here he opens 2 bags at a time and gets 13 and 13 Pistons.

He once got 7 Electric Pistons and once something totally different. But that is 5x the same stuff from 7 bags

**Comment by dries007** [comment]
Which item is the piston?

**Comment by dries007** [comment]
Sorry to say this, but I think this is because the Minecraft loot gen sucks. I can't do much about this, without a complete overhaul. We already use the World based random instance, can't do much more.
