### ISSUE TITLE
Expected name to be an item, was unknown string

### ISSUE THREAD

**Issue by akunaakwei** [DoubleDoorDevelopment/JsonLootBags#7]
Full log: http://pastebin.com/3tCp7SUU
My bags config: http://pastebin.com/KqpZpMUN
My loot table config: http://pastebin.com/kfaeCfBD

If you try to use items from mods, which are loaded after the JsonLootBags mod, you get this crash.

**A temporary workaround is renaming the file from "JsonLootBags-1.9.4-1.0.0.10.jar" to "_Z_JsonLootBags-1.9.4-1.0.0.10".**

Let me know if you need anything else, this is my first bug report.

**Comment by Claycorp** [comment]
Dries is on vacation currently and I can't fix this. He should be back next week. Sorry for the inconvenience.

**Comment by dries007** [comment]
Yes, I forgot about mod ordering when I made this. It registers the recipes on pre-init, instead of init like it should. I cannot fix this on my laptop without a lot of effort, so since you found an easy fix I'll wait until I get back.

**Comment by thephoenixlodge** [comment]
Just ran into this myself, and notice there has been no release since the fix was implemented. Is there a reason for this (something incomplete?) and if not, would it be possible to have this fix released?

**Comment by dries007** [comment]
It was made, but I forgot to upload it to curseforge. Its been uploaded just now.

**Comment by thephoenixlodge** [comment]
Awesome, thanks
